location = /couchdb {
    return 301 /couchdb/;
}

location /couchdb {
    rewrite ^ $request_uri;
    rewrite ^/couchdb/(.*) /$1 break;
    proxy_pass https://localhost:6984$uri;
    include /etc/nginx/includes/couchdb-common.conf;
}

location /_session {
    proxy_pass https://localhost:6984/_session;
    include /etc/nginx/includes/couchdb-common.conf;
}

