location = /couchdb {
    return 301 /couchdb/;
}

location ~ ^/couchdb/(?!_)([A-Za-z0-9][A-Za-z0-9_\-]*)/?$ {
    js_content api_key.check;
    rewrite ^/couchdb/([A-Za-z0-9][A-Za-z0-9_\-]*)(/|$) /$1/ break;
    proxy_pass https://localhost:6984;
    include /etc/nginx/includes/couchdb-common.conf;
}

location /couchdb {
    rewrite ^ $request_uri;
    rewrite ^/couchdb/(.*) /$1 break;
    proxy_pass https://localhost:6984$uri;
    include /etc/nginx/includes/couchdb-common.conf;
}

location /_session {
    proxy_pass https://localhost:6984/_session;
    include /etc/nginx/includes/couchdb-common.conf;
}

