all:
  children:
    servers:
      hosts:
        myserver:
          ansible_become: true
          ansible_become_exe: /usr/bin/sudo
          ansible_host: localhost
          server_crt: luna2.crt
          server_key: luna2.key
          server_name: couchdb
