---
containers:
  client1:
    image: client:latest
    networks:
      - ipv4: 172.16.1.101
        parent: lan1
        driver: bridge
        subnet: 172.16.1.0/24
        gateway: 172.16.1.1
      - ipv4: 172.31.0.101
        parent: admin
        driver: macvlan
        subnet: 172.31.0.0/24

  client2:
    image: client:latest
    networks:
      - ipv4: 172.16.2.102
        parent: lan2
        driver: bridge
        subnet: 172.16.2.0/24
        gateway: 172.16.2.1
      - ipv4: 172.31.0.102
        parent: admin
        driver: macvlan
        subnet: 172.31.0.0/24

  client3:
    image: client:latest
    networks:
      - ipv4: 172.16.3.103
        parent: lan3
        driver: bridge
        subnet: 172.16.3.0/24
        gateway: 172.16.3.1
      - ipv4: 172.31.0.103
        parent: admin
        driver: macvlan
        subnet: 172.31.0.0/24

  client4:
    image: client:latest
    networks:
      - ipv4: 172.16.4.104
        parent: lan4
        driver: bridge
        subnet: 172.16.4.0/24
        gateway: 172.16.4.1
      - ipv4: 172.31.0.104
        parent: admin
        driver: macvlan
        subnet: 172.31.0.0/24

  client5:
    image: client:latest
    networks:
      - ipv4: 172.16.5.105
        parent: lan5
        driver: bridge
        subnet: 172.16.5.0/24
        gateway: 172.16.5.1
      - ipv4: 172.31.0.105
        parent: admin
        driver: macvlan
        subnet: 172.31.0.0/24

  client6:
    image: client:latest
    networks:
      - ipv4: 172.16.6.106
        parent: lan6
        driver: bridge
        subnet: 172.16.6.0/24
        gateway: 172.16.6.1
      - ipv4: 172.31.0.106
        parent: admin
        driver: macvlan
        subnet: 172.31.0.0/24

  client7:
    image: client:latest
    networks:
      - ipv4: 172.16.7.107
        parent: lan7
        driver: bridge
        subnet: 172.16.7.0/24
        gateway: 172.16.7.1
      - ipv4: 172.31.0.107
        parent: admin
        driver: macvlan
        subnet: 172.31.0.0/24

environments:
  TZ: Asia/Tokyo
  LDAP_URI: ldaps://192.168.1.72
  LDAP_BASE: dc=example,dc=com
  LDAP_START_TLS: True
  LDAP_TLS_REQCERT: never
  LDAP_ALLOW_GROUPS: ldapusers

