---
ansible_host: myserver
ansible_become: true
#ansible_become_exe: /usr/bin/sudo

server_crt: myserver.crt
server_key: myserver.key

server_name: example.com

ssl_client_certificate: /etc/ssl/certs/mylocalca.pem

