---
- name: upload ssl_client_cert.conf 
  ansible.builtin.template:
    src:  ssl_client.conf
    dest: /etc/nginx/includes/

- name: find enabled-site
  ansible.builtin.find:
    paths: /etc/nginx/sites-enabled/
    recurse: no
    file_type: any
  register: res

- name: remove enabled sites
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ res.files }}"
  when: res.files | length > 0

- name: upload site_ssl_client
  ansible.builtin.template:
    src:  site_ssl_client
    dest: /etc/nginx/sites-available/site_ssl_client

- name: enable site_ssl_client
  ansible.builtin.file:
    src:  /etc/nginx/sites-available/site_ssl_client
    dest: /etc/nginx/sites-enabled/site_ssl_client
    state: link

- name: configure location
  ansible.builtin.template:
    src:  location.conf
    dest: /etc/nginx/includes/

- name: restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

