- name: setup zabbix server and agent
  hosts:
    - abaoaqu

  #environment:
  #  http_proxy: http://proxy.example.com:8080
  #  https_proxy: http://proxy.example.com:8080

  roles:
  - name: cacert
    tags: cacert

  - name: locale
    tags: locale

  - name: apache
    tags: apache

  - role: server
    tags: server

  - role: agent
    tags: agent

  - role: destroy
    tags: destroy, never

