---
- name: remove old keyring
  ansible.builtin.file:
    path: /usr/share/keyrings/elasticsearch-keyring.gpg
    state: absent

- name: add elasticsearch keyrings
  ansible.builtin.shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch \
    | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg

- name: install apt-transport-https
  ansible.builtin.apt :
    name: apt-transport-https
    state: present

- name: add source list
  ansible.builtin.shell: |
    echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/9.x/apt stable main" \
      | tee /etc/apt/sources.list.d/elastic-9.x.list

- name: install kibana
  ansible.builtin.apt :
    name: kibana
    state: present
    update_cache: true
 
- name: create config directory
  ansible.builtin.file:
    path:  /usr/share/kibana/config
    state: directory
    mode: '0755'
 
- name: create symbolic link
  ansible.builtin.file:
    src:  /etc/kibana/kibana.yml
    dest: /usr/share/kibana/config/kibana.yml
    owner: root
    group: kibana
    state: link

- name: create /etc/kibana/certs
  ansible.builtin.file:
    path:  /etc/kibana/certs
    owner: kibana
    group: kibana 
    state: directory

- name: copy kibana.key
  ansible.builtin.copy:
    src:  "{{ kibana_key }}"
    dest: /etc/kibana/certs/
    owner: kibana
    group: kibana
    mode: '0640'
  tags: config, ssl

- name: copy kibana.crt
  ansible.builtin.copy:
    src:  "{{ kibana_crt }}"
    dest: /etc/kibana/certs/
    owner: kibana
    group: kibana
    mode: '0644'
  tags: config, ssl

- name: replace server.host
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#?server\.host: ".*"$'
    replace: 'server.host: "0.0.0.0"'
  tags: config

- name: replace elasticsearch.hosts
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#?elasticsearch\.hosts: \[.*\]$'
    replace: 'elasticsearch.hosts: [ "{{ elasticsearch_hosts }}" ]'
  tags: config

- name: replace server.publicBaseUrl
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#?server\.publicBaseUrl: ".*"$'
    replace: 'server.publicBaseUrl: "{{ kibana_url }}"'
  tags: config

- name: replace server.ssl.enabled
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#?server\.ssl\.enabled: .*$'
    replace: 'server.ssl.enabled: true'
  tags: config

- name: replace server.ssl.certificate
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#?server\.ssl\.certificate: .*$'
    replace: 'server.ssl.certificate: /etc/kibana/certs/{{ kibana_crt }}'
  tags: config

- name: replace server.ssl.key
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#?server\.ssl\.key: .*$'
    replace: 'server.ssl.key: /etc/kibana/certs/{{ kibana_key }}'
  tags: config

- name: replace elasticsearch.username
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#?elasticsearch\.username: .*$'
    replace: 'elasticsearch.username: {{ kibana_username }}'
  tags: config

- name: replace elasticsearch.password
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#?elasticsearch\.password: .*$'
    replace: 'elasticsearch.password: {{ kibana_password }}'
  tags: config

- name: replace elasticsearch.ssl.verificationMode
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#?elasticsearch\.ssl\.verificationMode: .*$'
    replace: 'elasticsearch.ssl.verificationMode: none'
  tags: config

- name: disable OpenSSL 3 legacy provider
  ansible.builtin.lineinfile:
    path: /etc/kibana/node.options
    regexp: '^--openssl-legacy-provider'
    line: '#--openssl-legacy-provider'

- name: enable logrotate
  ansible.builtin.template:
    src: logrotate-kibana.conf
    dest: /etc/logrotate.d/kibana

- name: restart logrotate
  ansible.builtin.systemd_service:
    name: logrotate
    state: restarted
    enabled: true
    masked: no

- name: restart kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted
    enabled: true

