---
- name: upload deb package
  ansible.builtin.copy:
    src: dex_2.45.1_amd64.deb
    dest: /tmp/

- name: install deb package
  ansible.builtin.apt:
    deb: /tmp/dex_2.45.1_amd64.deb
    state: present

- name: change permission of /etc/dex
  ansible.builtin.file:
    path: /etc/dex
    state: directory
    owner: dex
    group: dex
    mode: '0775'
  
- name: make certs directory
  ansible.builtin.file:
    path: /etc/dex/certs/
    state: directory
    owner: dex
    group: dex
    mode: '0775'

- name: upload server crt
  ansible.builtin.copy:
    src: "{{ cert_file }}"
    dest: /etc/dex/certs/
    owner: dex
    group: dex
    mode: '0664'

- name: upload server key
  ansible.builtin.copy:
    src: "{{ key_file }}"
    dest: /etc/dex/certs/
    owner: dex
    group: dex
    mode: '0660'

- name: upload config
  ansible.builtin.template:
    src: config-ldap.yaml
    dest: /etc/dex/

- name: start service
  ansible.builtin.systemd_service:
    name:  dex
    state: restarted

