
listen 443 ssl;
server_name {{ server_addr }};

ssl_certificate     /etc/nginx/certs/{{ server_crt }};
ssl_certificate_key /etc/nginx/certs/{{ server_key }};
ssl_protocols TLSv1.3;
ssl_session_cache shared:SSL:1m;

