#https://hub.docker.com/r/elastic/filebeat

volumes:
  filebeat-config:
    name: filebeat-config
  filebeat-data:
    name: filebeat-data

services:
  filebeat:
    image: elastic/filebeat:9.3.4
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    stdin_open: true   # docker run -i
    tty:        true   # docker run -t
    environment:
      TZ: Asia/Tokyo
    user: root
    volumes:
    - /var/log:/var/log:ro
    - filebeat-config:/usr/share/filebeat
    - filebeat-data:/usr/share/filebeat/data
    command: ["--strict.perms=false"]

