lua_package_path "/usr/lib/lua/5.1/?.lua;/usr/lib/lua/5.1/?/init.lua;/usr/lib/lua/5.1/resty/?.lua;/usr/lib/lua/5.1/resty/?/init.lua;;";
lua_package_cpath "/usr/lib/lua/5.1/?.so;/usr/lib/lua/5.1/resty/?.so;;";

