input {
  file {
    mode => "tail"
    path => [ "/var/log/*.log" ]
    sincedb_path => "/var/lib/logstash/sincedb-dummy"
    start_position => "beginning"
    codec => plain {
      charset => "UTF-8"
    }
  }
}

output {
  stdout {
    codec => rubydebug {
      metadata => true
    }
  }
}

