volumes:
  couchdb-config:
    name: couchdb-config
  couchdb-data:
    name: couchdb-data

  nginx-config:
    name: nginx-config
  nginx-data:
    name: nginx-data

networks:
  couchdb-net:
    name: couchdb-net
    driver: bridge
    internal: true
  nginx-net:
    name: nginx-net
    driver: bridge

services:
  nginx:
    image: nginx:${NGINX_VERSION}-alpine-perl
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-config:/etc/nginx
      - nginx-data:/usr/share/nginx/html
    networks:
      - couchdb-net
      - nginx-net

  couchdb:
    image: couchdb:${COUCHDB_VERSION}
    container_name: couchdb
    hostname: couchdb
    #ports:
    #  - "5984:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      - couchdb-config:/opt/couchdb/etc/local.d
      - couchdb-data:/opt/couchdb/data
    networks:
      - couchdb-net


