---
services:
  parrot:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart:  always
    stdin_open: true   # docker run -i
    tty:        true   # docker run -t
    environment:
      TZ: Asia/Tokyo
    ports:
      - "${SSH_LPORT}:22"
    networks:
      inet_macvlan:
        ipv4_address: 192.168.0.42

networks:
  inet_macvlan:
    external: true
