filter {
  if [@metadata][filebeat_id] == "embeddings" {
    if [message] {
      json {
        source => "message"
        target => ""
      }
    }
  }
}

filter {
  if [@metadata][filebeat_id] {
    mutate {
      add_field => { "[@metadata][target_index]" => "%{[@metadata][filebeat_id]}" }
    }  
  }
  else {
    mutate {
      add_field => { "[@metadata][target_index]" => "default" }
    }  
  }
}

filter {
  if ([@metadata][filebeat_id] and [@metadata][filebeat_id] == "mycsv") {
    if [message] =~ /^id,/ {
      drop { }
    }
    else {
      csv {
        separator => ","
        columns => [ "id", "key", "value" ]
      }
      mutate {
        strip => [ "id", "key", "value" ]
      }
    }
  }
}

