filter {
  if ([@metadata][filebeat_id] and [@metadata][filebeat_id] == "mycsv") {
    if [message] =~ /^id,/ {
      drop { }
    }
    else {
      csv {
        separator => ","
        columns => [ "id", "key", "value" ]
      }
      mutate {
        strip => [ "id", "key", "value" ]
      }
    }
  }
}


