input {
  http {
    port => 8080
  }
}

filter {
  
}

output {
  elasticsearch {
    hosts => [ "{{ elastic_url }}" ]
    index => "fluentbit-%{+YYYY.MM.dd}"
    api_key => "{{ api_key_id }}:{{ api_key }}"
    ssl_enabled => true
    ssl_verification_mode => "full"
    #ssl_verification_mode => "none"
    ssl_certificate_authorities => "/etc/ssl/certs/ca-certificates.crt"
    action => "create"
  }
}

