all:
  children:
    servers:
      hosts:
        myserver:
          admin_passwd: secret
          ansible_become: true
          ansible_host: abaoaqu
          bind_address: 0.0.0.0
          couch_http_port: 5984
          couch_https_port: 6984
          server_addr: 192.168.1.98
          server_crt: abaoaqu.crt
          server_key: abaoaqu.key
