- name: delete linux bridges
  ansible.builtin.shell: |
    num=`nmcli --fields name con show | grep -e '^{{ item.name }}$' | wc -l`
    if [ "$num" -ne 0 ]; then
      sudo nmcli con del {{ item.name }}
    fi
  loop: "{{ bridges }}"
  
- name: create linux bridges
  ansible.builtin.shell: |
    nmcli con add \
      type bridge \
      ifname {{ item.name }} \
      conn.id {{ item.name }} \
      ipv4.method disable \
      ipv6.method disable
  loop: "{{ bridges }}"
  
