---
- name: install NetworkManager
  ansible.builtin.shell: |
    arch-chroot /mnt \
      pacman -S --noconfirm networkmanager

- name: enable NetworkManager
  ansible.builtin.shell: |
    arch-chroot /mnt \
      systemctl enable NetworkManager

- name: enable sshd
  ansible.builtin.shell: |
    arch-chroot /mnt \
      systemctl enable sshd

