- name: setup apache and jenkins
  hosts: localhost

  roles:
  #- name: apache
  #  tags: apache
  
  #- name: sslrequire
  #  tags: sslrequire

  - name: jenkins
    tags: jenkins

  - name: nginx
    tags: nginx

