---
bridges:
  - name: admin
    ipv4.method: manual
    ipv4.addresses: 172.31.0.1/24
    ipv6.method: disable

networks:
  - name: admin_macvlan
    parent: admin
    driver: macvlan
    subnet: 172.31.0.0/24

  - name: inet_macvlan
    parent: inet
    driver: macvlan
    subnet: 172.16.0.0/24
    gateway: 172.16.0.1

