Section "Device"
    Identifier "dummy"
    Driver "dummy"
    VideoRam 256000
EndSection

Section "Monitor"
    Identifier "monitor"
    HorizSync 30-70
    VertRefresh 50-75
EndSection

Section "Screen"
    Identifier "screen"
    Device "dummy"
    Monitor "monitor"
    SubSection "Display"
        Depth 24
        Modes "1280x960"
    EndSubSection
EndSection

