---
services:
  noble:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart:  always
    stdin_open: true   # docker run -i
    tty:        true   # docker run -t
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
    ports:
      - "${SSH_LPORT}:22"
      #- "${HTTP_LPORT}:8080"
      - "${HTTPS_LPORT}:8443"
