server {
    listen 443 ssl;
    server_name 192.168.1.72;

    ssl_certificate     /etc/ssl/certs/server.crt;
    ssl_certificate_key /etc/ssl/private/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    #root /usr/share/nginx/html;
    root /usr/share/novnc;
    index index.html;

    auth_pam "LDAP Login";
    auth_pam_service_name "nginx";

    location /websockify {
        proxy_pass http://localhost:6080; # ← websockify-c が LISTEN するポート
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
}

