[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true

[program:sssd]
command=/usr/sbin/sssd -i --logger=files
autostart=true
autorestart=true

[program:xvnc]
command=/usr/bin/Xvnc :0 -geometry 1280x960 -depth 24 -rfbport 5900 -SecurityTypes=None
autorestart=true
priority=20

[program:websockify]
command=/usr/bin/websockify --web=/usr/share/novnc --cert /etc/ssl/certs/server.crt --key  /etc/ssl/private/server.key 8443 localhost:5900
autorestart=true
priority=30

[program:xfce4]
command=/usr/bin/xfce4-session
environment=DISPLAY=":0"
autorestart=true
priority=40

