[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true

[program:sssd]
command=/usr/sbin/sssd -i --logger=files
autostart=true
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=15

[program:init_dbus]
command=/bin/sh -c "mkdir -p /run/dbus && rm -f /run/dbus/pid"
autostart=true
autorestart=false
startsecs=0
exitcodes=0
priority=1

[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork
autostart=true
autorestart=true
priority=5

[program:lightdm]
#command=/usr/sbin/lightdm
command=/usr/local/bin/lightdm-wrapper.sh
autorestart=true
priority=10

[program:x11vnc]
#command=/usr/bin/x11vnc -display :0 -auth /var/run/lightdm/root/:0 -forever -shared -nopw -rfbport 5900 -quiet
command=/usr/local/bin/x11vnc-wrapper.sh
environment=HOME="/root",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
autorestart=true
priority=50
startsecs=5

[program:websockify]
command=/usr/local/bin/websockify-c 6080 localhost:5900
autorestart=true
priority=30
stopasgroup=true
killasgroup=true
startsecs=1
startretries=3


