---
- name: create certs directory
  ansible.builtin.file:
    path: /etc/nginx/certs
    state: directory

- name: upload server crt
  ansible.builtin.copy:
    src: "{{ server_crt }}"
    dest: /etc/nginx/certs

- name: upload server key
  ansible.builtin.copy:
    src: "{{ server_key }}"
    dest: /etc/nginx/certs
    owner: root
    group: root
    mode: '600'

- name: make includes directory
  ansible.builtin.file:
    path: /etc/nginx/includes
    state: directory

- name: configure default location
  ansible.builtin.template:
    src:  location-default.conf
    dest: /etc/nginx/includes/

- name: upload ssl.conf
  ansible.builtin.template:
    src:  ssl.conf
    dest: /etc/nginx/includes/

- name: find enabled-site
  ansible.builtin.find:
    paths: /etc/nginx/sites-enabled/
    recurse: no
    file_type: any
  register: res

- name: remove enabled sites
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ res.files }}"
  when: res.files | length > 0

- name: upload site_ssl
  ansible.builtin.template:
    src: site_ssl
    dest: /etc/nginx/sites-available/

- name: enable site_ssl
  ansible.builtin.file:
    src:  /etc/nginx/sites-available/site_ssl
    dest: /etc/nginx/sites-enabled/site_ssl
    state: link

- name: restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

