TLSConnect=cert
TLSAccept=cert
TLSCAFile=/etc/ssl/certs/ca-certificates.crt
TLSCertFile=/etc/ssl/certs/zabbix_agent.crt
TLSKeyFile=/etc/ssl/private/zabbix_agent.key

Server={{ server_ip }}
ServerActive={{ server_ip }}



