server {
    server_name _;

    include /etc/nginx/includes/ssl.conf;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    include /etc/nginx/includes/couchdb-location.conf;

    include /etc/nginx/includes/default-location.conf;
}

