#!/bin/sh

# https://bytexd.com/how-to-install-configure-vnc-server-on-ubuntu/

# Start up the standard system desktop
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# for Xfce
#/usr/bin/startxfce4

# for KDE plasma
/usr/bin/startplasma-x11

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
x-window-manager &

