---
- name: uninstall nginx
  ansible.builtin.apt:
    name:
    - nginx
    - nginx-common
    - libnginx-mod-http-auth-pam
    state: absent
    purge: true

- name: remove /etc/nginx
  ansible.builtin.file:
    path: /etc/nginx
    state: absent

