---
- name: install java for ssh build agent
  ansible.builtin.apt:
    name:
    - openjdk-25-jre-headless
    update_cache: true

#- name: add jenkins group (not install package)
#  ansible.builtin.group:
#    name: jenkins
#    state: present
#    gid: 147
#    system: true

- name: add jenkins group (not install package)
  ansible.builtin.shell: |
    addgroup --system --quiet "{{ agent_group }}"

#- name: add jenkins user (not install package)
#  ansible.builtin.user:
#    name: jenkins
#    group: jenkins
#    groups: jenkins
#    state: present
#    uid: 147
#    home: /var/lib/jenkins
#    shell: /bin/bash
#    comment: Jenkins
#    system: true

- name: add agent user (not install package)
  ansible.builtin.shell: |
    adduser --system --quiet \
      --home /var/lib/agent \
      --ingroup "{{ agent_user }}" \
      --disabled-password \
      --shell /bin/bash \
      --gecos "{{ agent_user }}" \
      "{{ agent_user }}"

- name: change permission of home directory
  ansible.builtin.file:
    path: "/var/lib/agent"
    owner: "{{ agent_user }}"
    group : "{{ agent_group }}"
    recurse: true

- name: generate ssh key
  ansible.builtin.shell: |
    sudo -u "{{ agent_user }}" bash << EOF
      mkdir -p /var/lib/agent/.ssh
      cd /var/lib/agent/.ssh
      if [ ! -e id_ed25519 ]; then
        ssh-keygen -t ed25519 -f id_ed25519 -N ""
      fi
      cp -f id_ed25519.pub authorized_keys
    EOF

- name: remove agent user (not remove package)
  ansible.builtin.user:
    name: "{{ agent_user }}"
    state: absent
  tags: remove, never

- name: remove agent group (not remove package)
  ansible.builtin.group:
    name: "{{ agent_group }}"
    state: absent
  tags: remove, never

