---
- name: install java for ssh build agent
  ansible.builtin.apt:
    name:
    - openjdk-25-jre-headless
    update_cache: true

- name: add jenkins group (not install package)
  ansible.builtin.group:
    name: jenkins
    state: present
    gid: 147
    system: true

- name: add jenkins user (not install package)
  ansible.builtin.user:
    name: jenkins
    group: jenkins
    groups: jenkins
    state: present
    uid: 147
    home: /var/lib/jenkins
    shell: /bin/bash
    comment: Jenkins
    system: true

- name: change permission of home directory
  ansible.builtin.file:
    path: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    recurse: true

- name: generate ssh key
  ansible.builtin.shell: |
    cd /var/lib/jenkins
    sudo -u jenkins mkdir -p /var/lib/jenkins/.ssh
    if [ ! -e /var/lib/jenkins/.ssh/id_ed25519 ]; then
      sudo -u jenkins ssh-keygen -t ed25519 -f /var/lib/jenkins/.ssh/id_ed25519 -N ""
    fi
    sudo -u jenkins cp -f /var/lib/jenkins/.ssh/id_ed25519.pub /var/lib/jenkins/.ssh/authorized_keys

