DBPassword={{ zabbix_pw }}

TLSCAFile=/etc/ssl/certs/ca-certificates.crt
TLSCertFile=/etc/zabbix/certs/zabbix_server.crt
TLSKeyFile=/etc/zabbix/certs/zabbix_server.key

NodeAddress=localhost:10051

SSLCALocation=/etc/zabbix/certs
