---
ansible_host: myserver
ansible_become: true
ansible_become_exe: /usr/bin/sudo.ws

server_crt: server.crt
server_key: server.key

server_ip: 192.168.1.98

# for /etc/cockpit/cockpit.conf
origins: https://192.168.1.98 wss://192.168.1.98

