[chttpd]
; disable http connection
;port = 5984
port = 0
;bind_address = 0.0.0.0
bind_address = 127.0.0.1

[ssl]
enable = true
port = 6984
cert_file = /opt/couchdb/etc/certs/couchdb.crt
key_file  = /opt/couchdb/etc/certs/couchdb.key

; set to true to validate peer certificates
verify_ssl_certificates = false

; Set to true to fail if the client does not send a certificate. Only used if verify_ssl_certificates is true.
fail_if_no_peer_cert = false

; Path to file containing PEM encoded CA certificates (trusted
; certificates used for verifying a peer certificate). May be omitted if
; you do not want to verify the peer.
cacert_file = /etc/ssl/certs/ca-certificates.crt

