volumes:
  couchdb-config:
    name: couchdb-config
  couchdb-certs:
    name: couchdb-certs
  couchdb-data:
    name: couchdb-data

networks:
  traefik-net:
    name: traefik-net
    external: true

services:
  couchdb:
    image: couchdb:${COUCHDB_VERSION}
    container_name: couchdb
    hostname: couchdb
    networks:
      traefik-net:
        ipv4_address: 172.31.0.10
    #ports:
    #- "6984:6984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      - couchdb-config:/opt/couchdb/etc/local.d
      - couchdb-certs:/opt/couchdb/etc/certs
      - couchdb-data:/opt/couchdb/data
    env_file:
    - .env

