volumes:
  couchdb-config:
    name: ${NAME}-config
  couchdb-certs:
    name: ${NAME}-certs
  couchdb-data:
    name: ${NAME}-data

services:
  couchdb:
    image: ${NAME}:${COUCHDB_VERSION}
    container_name: ${NAME}
    hostname: ${NAME}
    network_mode: host
    #ports:
    #- "5984:5984"
    #- "6984:6984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      - ${NAME}-config:/opt/couchdb/etc/local.d
      - ${NAME}-certs:/opt/couchdb/etc/certs
      - ${NAME}-data:/opt/couchdb/data
    env_file:
    - .env

