# Install Docker Engine on Ubuntu
# https://docs.docker.com/engine/install/ubuntu/

- name: deploy docker
  hosts: myserver
  
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBCONF_NONINTERACTIVE_SEEN: "true"      # 既に回答済みとして扱う
    NEEDRESTART_MODE: a                    # needrestartを自動モードに
    NEEDRESTART_SUSPEND: 1                 # 一時的にsuspend
  
  #  http_proxy: http://proxy.example.com:8080
  #  https_proxy: http://proxy.example.com:8080

  tasks:
  - name: uninstall old versions
    ansible.builtin.apt:
      name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      state: absent
  
  - name: install ca-certificates and curl
    ansible.builtin.apt:
      name:
      - ca-certificates
      - curl
      state: present
      update_cache: true

  - name: download GPG key
    ansible.builtin.shell: |
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc

  - name: download GPG key
    ansible.builtin.shell: |
      arch=$(dpkg --print-architecture)
      docker_asc=/etc/apt/keyrings/docker.asc
      url=https://download.docker.com/linux/ubuntu
      code=$(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
      echo \
        "deb [arch=$arch signed-by=$docker_asc] $url $code stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
  
  - name: install containerd.io
    ansible.builtin.apt:
      name:
      - containerd.io
      state: present
      update_cache: true
  
  - name: install docker-ce
    ansible.builtin.apt:
      name:
      - docker-ce
      - docker-ce-cli
      state: present
      update_cache: true

 
  - name: install docker compose
    ansible.builtin.apt:
      name:
      - docker-compose-plugin
      state: present
      update_cache: true
  
  - name: install docker buildx plugin
    ansible.builtin.apt:
      name:
      - docker-buildx-plugin
      state: present
      update_cache: true


