location /lua/jwks {
    default_type text/plain;
    content_by_lua_block {
        local http = require "resty.http"
        local cjson = require "cjson"

        local client = http.new()
        local res, err = client:request_uri("{{ dex_keys_url }}", {
            method = "GET",
            ssl_verify = false,
        })
        if not res then
            ngx.say("HTTP error: ", err)
            return
        end
        ngx.say("Status: ", res.status)
        ngx.say("Body: ", res.body)
    }
}

