TLSConnect=cert
TLSAccept=cert
TLSCAFile=/etc/ssl/certs/ca-certificates.crt
TLSCertFile=/etc/ssl/certs/{{ agent_crt }}
TLSKeyFile=/etc/ssl/private/{{ agent_key }}

Server={{ server_ip }}
ServerActive={{ server_ip }}



