---
- name: upload api_keys.conf
  ansible.builtin.template:
    src: api_keys.conf
    dest: /etc/nginx/conf.d/
    owner: root
    group: www-data
    mode: '0640'

- name: update couchdb.conf with api_key
  ansible.builtin.template:
    src: couchdb.conf
    dest: /etc/nginx/includes/
    owner: root
    group: www-data
    mode: '0640'

- name: restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

