#if ($request_uri = "/couchdb/_utils") {
#  return 301 /couchdb/_utils/;
#}
#if ($request_uri = "/couchdb") {
#  return 301 /couchdb/;
#}
#rewrite ^/couchdb/?(.*)$ /$1 break;

rewrite ^/couchdb$ /couchdb/ permanent;
rewrite ^/couchdb/(.*)$ /$1 break;

#auth_pam "PAM Authentication";
#auth_pam_service_name "nginx";

#set $user $remote_user;

#if ($user = "") {
#  set $user $http_authorization;
#}

# 認証成功時に CouchDB Proxy Auth 用ヘッダを付与
#proxy_set_header X-Auth-CouchDB-UserName $user;
#proxy_set_header X-Auth-CouchDB-Roles "user";
#proxy_set_header X-Auth-CouchDB-Token "static";

proxy_pass https://localhost:6984/;
proxy_ssl_verify off;

proxy_set_header Host $host;
proxy_http_version 1.1;
proxy_set_header Connection "";
#proxy_read_timeout 86400;

