---
ansible_host: abaoaqu
ansible_become: true

cacert: myrootca.crt
caname: MyRootCA

server_crt: abaoaqu.crt
server_key: abaoaqu.key


zabbix_server_name: abaoaqu 

zabbix_user: zabbix
zabbix_pw: password
zabbix_db: zabbix

