---
#- name: copy CA cert
#  ansible.builtin.copy:
#    src:   "{{ cacert }}"
#    dest:  "{{ certs_dir }}"
#    owner: root
#    group: root 
#    mode:  '0644'

- name: upload cacert
  ansible.builtin.copy:
    src: "{{ cacert }}"
    dest: /usr/local/share/ca-certificates/

- name: update ca certificates
  ansible.builtin.shell: |
    update-ca-certificates

- name: create certs directory
  ansible.builtin.file:
    path:  "{{ certs_dir }}"
    state: directory
    owner: root
    group: root 
    mode:  '0755'

- name: copy client cert
  ansible.builtin.copy:
    src:   "{{ client_cert }}"
    dest:  "{{ certs_dir }}"
    owner: root
    group: root 
    mode:  '0644'

- name: copy client key
  ansible.builtin.copy:
    src:   "{{ client_key }}"
    dest:  "{{ certs_dir }}"
    owner: root
    group: root 
    mode:  '0600'

