volumes:
  dex-config:
    name: dex-config
  dex-data:
    name: dex-data

services:
  dex:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    command: ["dex", "serve", "/etc/dex/config-ldap.yaml"]
    #network_mode: bridge
    ports:
    - "${DEX_PORT}:${DEX_PORT}"
    #environment:
    volumes:
      - dex-config:/etc/dex
      - dex-data:/var/lib/dex
    env_file:
    - .env

