---
- name: install Zabbix repository
  ansible.builtin.apt:
    deb: "{{ zabbix_repo_url }}"

- name: apt update, install Zabbix agent
  ansible.builtin.apt:
    name:
    - zabbix-agent
    update_cache: yes

- name: upload server cert
  ansible.builtin.copy:
    src: "{{ server_crt }}"
    dest: /etc/ssl/certs/
    mode: '0644'

- name: upload server key
  ansible.builtin.copy:
    src: "{{ server_key }}"
    dest: /etc/ssl/private/
    mode: '0640'
    owner: root
    group: ssl-cert

- name: upload agent configuration
  ansible.builtin.template:
    src: local.conf
    dest: /etc/zabbix/zabbix_agentd.d/

- name: allow zabbix agent to read SSL certificates
  ansible.builtin.user:
    name: zabbix
    groups:
    - ssl-cert
    append: yes
    state: present

- name: restart zabbix-agent
  ansible.builtin.systemd_service:
    name: zabbix-agent
    state: restarted

