- name: setup zabbix agent
  hosts:
    - example

  #environment:
  #  http_proxy: http://proxy.example.com:8080
  #  https_proxy: http://proxy.example.com:8080

  roles:
  - role: agent
    tags: agent

  - role: destroy
    tags: destroy, never

